### ISSUE TITLE
logging 시스템 구축하기

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/wisdomify#17]
로깅을 할 수 있어야 한다.
가능하면 tensorboard로.
 
## To-do's
- [x] : 먼저 pytorch-lightning에서 로깅을 어떻게 진행하는지에 대한 이해가 필요함.
- [x] : forward 함수 return 값을 dictionary로 바꾸기. (i.e. `batch_dict` 반환하기)
- [x] : 매 epoch마다, training performance 측정하기 & 그걸 로깅하기.
- [ ] : 수정이 필요하다. 뭔가 잘못된 부분이 있는 듯.

**Comment by eubinecto** [comment]
## PL에서 로깅을 어떻게 진행하는지에 대한 이해를 하기

**Comment by ArtemisDicoTiar** [comment]
혹시 이런 형태로 로깅하고 싶은거야?? @eubinecto 
[링크](https://tensorboard.dev/experiment/l0dxBTxbSnGHY3npXySaGg/#scalars)
실제로 version_0 training으로 텐서보드로 로깅해봤는데 이런게 필요한건지?

### 방법
#### main.train
logger만 추가하면 된다. (*주의 사항: savd_dir을 정확히 지정해야한다. relative directory로 지정시 파이썬 실행 명령을 실행한 디렉토리를 "./"로 지정하기 때문에 엉뚱한 위치에 로그들이 저장될 수 있다.)

~~~python
# --- instantiate the trainer --- #
logger = TensorBoardLogger(save_dir="{logging save_dir}", name="wisdomify", version=0)
trainer = pl.Trainer(gpus=torch.cuda.device_count(),
                     max_epochs=max_epochs,
                     callbacks=[checkpoint_callback],
                     default_root_dir=DATA_DIR,
                     logger=logger)
# --- start training --- #
trainer.fit(model=rd,
            train_dataloader=dataloader)
~~~

해당 save_dir에 로깅파일들이 생긴다.
이제 해당 디렉토리 텐서보드를 열면된다.
주피터 노트북에서 아래 코드를 실행하면 된다.
~~~python
%load_ext tensorboard

%tensorboard --logdir {logging save_dir}
~~~
해당 코드를 주피터 노트북에서 실행하면 해당 cell에서 바로 텐서보드 화면이 열린다.

해당 텐서보드를 공유하기 위해서는 아래 명령어를 terminal에서 실행후 구글 계정을 연결하기만 하면 된다. (링크가 생성됨)
~~~
tensorboard dev upload --logdir \
    '{로깅 저장한 디렉토리 → 위의 save_dir}'

~~~

**Comment by eubinecto** [comment]
## 다시 개발시작

아... logger와 trainer에 `version` paramter가 있는줄 몰랐네. @ArtemisDicoTiar 고마워!  이걸로  버전 컨트롤이 좀 더 쉬워질듯!

**Comment by eubinecto** [comment]
테스트 하나가 fail 했길래, 왜지 싶었는데...  `training_step`이 이제는 `dict`를 출력하기 때문이었다.

다음과 같이 loss를 dict에서 꺼내는 식으로 수정함:
```python3
    def test_training_step_dim(self):
        # (N, 3, L) -> scalar
        loss = self.rd.training_step((self.X, self.y), 0)['loss']
        self.assertEqual(len(loss.shape), 0)  # should be a scalar

```
