### ISSUE TITLE
Training on Ainize server (GPU resource)

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [eubinecto/wisdomify#26]
## ISSUE
* Explanation: 
  * GPU 리소스가 있는 서버에서는 트레이닝이 실행되지 않는다. 
* Error Traceback:
~~~
Traceback (most recent call last):
  File “/opt/conda/lib/python3.7/runpy.py”, line 193, in _run_module_as_main
    “_main_“, mod_spec)
  File “/opt/conda/lib/python3.7/runpy.py”, line 85, in _run_code
    exec(code, run_globals)
  File “/workspace/wisdomify/wisdomify/main/train.py”, line 80, in <module>
    main()
  File “/workspace/wisdomify/wisdomify/main/train.py”, line 74, in main
    train_dataloader=dataloader)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py”, line 460, in fit
    self._run(model)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py”, line 758, in _run
    self.dispatch()
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py”, line 799, in dispatch
    self.accelerator.start_training(self)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py”, line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py”, line 144, in start_training
    self._results = trainer.run_stage()
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py”, line 809, in run_stage
    return self.run_train()
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py”, line 871, in run_train
    self.train_loop.run_training_epoch()
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py”, line 491, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/profiler/profilers.py”, line 112, in profile_iterable
    value = next(iterator)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/supporters.py”, line 530, in prefetch_iterator
    last = next(it)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/supporters.py”, line 464, in _next_
    return self.request_next_batch(self.loader_iters)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/supporters.py”, line 478, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py”, line 85, in apply_to_collection
    return function(data, *args, **kwargs)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py”, line 521, in _next_
    data = self._next_data()
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py”, line 1203, in _next_data
    return self._process_data(data)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py”, line 1229, in _process_data
    data.reraise()
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/torch/_utils.py”, line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py”, line 287, in _worker_loop
    data = fetcher.fetch(index)
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py”, line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py”, line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File “/workspace/wisdomify/wisdomify/datasets.py”, line 39, in _getitem_
    return self.X[idx], self.y[idx]
RuntimeError: CUDA error: initialization error
Exception ignored in: <function tqdm._del_ at 0x7f28f6f63170>
Traceback (most recent call last):
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/tqdm/std.py”, line 1145, in _del_
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/tqdm/std.py”, line 1299, in close
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/tqdm/std.py”, line 1492, in display
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/tqdm/std.py”, line 1148, in _str_
  File “/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/tqdm/std.py”, line 1450, in format_dict
TypeError: cannot unpack non-iterable NoneType object
~~~

## How to reproduce
* Branch: main
* details:
CLI에서 python -m wisdomify.main.train 실행시 발생함.
CPU 자원만 가능한 시스템에서는 문제 발생하지 않음. CUDA사용환경에서 해결 필요.

----
@eubinecto 
## To-do's
- [x]  ainize 플랫폼에서 `infer.py`가 안되는데, 이것도 다시한번 고쳐보기 (아마도 또 디바이스에 안올려서 그렇게 된 것일 것)
- [ ] ainize 플랫폼에서 version_0 training 실행해보기
- [ ] `version_1` 데이터 수정하기

**Comment by eubinecto** [comment]
## 문제가 무엇일까?

**Comment by eubinecto** [comment]
```
0,가는 날이 장날,하지만 가는 날이 장날이다.
```
이건 내가 해결해야할 듯.

**Comment by eubinecto** [comment]
## To-do's
- [ ] `version_1` 데이터 수정하기
- [ ]  ainize 플랫폼에서 `infer.py`가 안되는데, 이것도 다시한번 고쳐보기 (아마도 또 디바이스에 안올려서 그렇게 된 것일 것)

**Comment by eubinecto** [comment]
## 문제
```
(wisdomifyenv) root@owzeywysbowkytjestgbmfco-69f949b44f-vcnd9:~/wisdomify# python3 -m wisdomify.main.infer
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 619/619 [00:00<00:00, 368kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49.0/49.0 [00:00<00:00, 47.5kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 250k/250k [00:00<00:00, 844kB/s]
### desc: 왜 하필이면 오늘이야 ###
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/wisdomify/wisdomify/main/infer.py", line 33, in <module>
    main()
  File "/workspace/wisdomify/wisdomify/main/infer.py", line 27, in main
    for results in wisdomifier.wisdomify(sents=[desc]):
  File "/workspace/wisdomify/wisdomify/models.py", line 150, in wisdomify
    S_word = self.rd.S_word(S_subword)
  File "/workspace/wisdomify/wisdomify/models.py", line 58, in S_word
    S_word = S_subword.gather(dim=-1, index=word2subs)  # (N, K, |S|) -> (N, K, |V|)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument index in method wrapper_gather)
(wisdomifyenv) root@owzeywysbowkytjestgbmfco-69f949b44f-vcnd9:~/wisdomify# 
```
엥...? 저번엔 잘만되더니.. 왜 지금은 또 not on the same device 오류가 뜨는걸까?


## 해결
아, #39 이 문제를 해결하는 과정 속에서 바꾼 코드가 문제였네.
`from_pretrained`안에서, `rd`를 `device`에 올려주질 않았다.

**Comment by eubinecto** [comment]
## ainize 플랫폼에서 `verision_0` 훈련해보기

이게 안되는 것이 문제였다. 일단 실행은 해보자..

**Comment by ArtemisDicoTiar** [comment]
[이 페이지](https://pytorch.org/docs/stable/data.html)의 Single- and Multi-process Data Loading 이 토픽 확인해봐!
지금 에러 나는 이유가 데이터로더에서 나는 건데
쿠다에서 sharing 텐서가 안되는 거 같음 ㅠ

**Comment by eubinecto** [comment]
> [이 페이지](https://pytorch.org/docs/stable/data.html)의 Single- and Multi-process Data Loading 이 토픽 확인해봐!
> 지금 에러 나는 이유가 데이터로더에서 나는 건데
> 쿠다에서 sharing 텐서가 안되는 거 같음 ㅠ

ㅇㅇㅇㅇ 아무리봐도... 멀티프로세싱과 관련이 있는 듯ㅠㅠ

<img width="487" alt="image" src="https://user-images.githubusercontent.com/56193069/128616290-a90862ae-afe6-4260-bb73-7c932bba5424.png">

`num_workers`를 0으로 설정하면,  `train.py`가 문제없이 돌아가는 것을 확인함:
```
(wisdomifyenv) root@owzeywysbowkytjestgbmfco-69f949b44f-vcnd9:~/wisdomify# python3 -m wisdomify.main.train --ver="0"
Some weights of the model checkpoint at beomi/kcbert-base were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py:99: UserWarning: you passed in a val_dataloader but have no validation_step. Skipping val loop
  rank_zero_warn(f'you passed in a {loader_name} but have no {step_name}. Skipping {stage} loop')
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type            | Params
----------------------------------------------
0 | bert_mlm  | BertForMaskedLM | 108 M 
1 | rd_metric | RDMetric        | 0     
----------------------------------------------
108 M     Trainable params
0         Non-trainable params
108 M     Total params
435.800   Total estimated model params size (MB)
Epoch 0:  75%|███████████████████████████████████████████████████████████████                     | 15/20 [00:04<00:01,  3.33it/s, loss=5.84, v_num=2]
```

**Comment by eubinecto** [comment]
어쩔수가 없다. 이 문제를 해결하기전까지는, num_workers는 무조건 0으로 고정을 하자.
아마도 오버헤드 warning이 뜨긴하겠지만, gpu를 못쓰는 것보단 낫겠지.
