### ISSUE TITLE
사전훈련  wisdomify 로드를 간단하게!

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/wisdomify#39]
## Why?

duplicated fragments가 있음:
여기에 한번:
https://github.com/eubinecto/wisdomify/blob/15c810adeafd3b8276baa122b5fe40c3a148ebbd/wisdomify/main/infer.py#L38-L44

여기에 두번:
https://github.com/eubinecto/wisdomify/blob/15c810adeafd3b8276baa122b5fe40c3a148ebbd/wisdomify/main/eval.py#L46-L52

이거를 한줄로 끝낼 수 있는 함수가 필요함.

## How?

허깅 페이스 라이브러리처럼.. 이렇게 해버리는 것도 좋을듯!
```python3
wisdomifier = Wisdomifier.from_pretrained("0")
```

## To-do's
- [x] `infer.py`가 지금 실행이 안되는데, 이것부터 픽스하기.
- [x]  `from_pretrained` 함수 구현하기.
- [x] `infer.py` &  `eval.py` 확인하기.

**Comment by eubinecto** [comment]
아... 모델과 데이터 버전이 따로노니까 이런 문제가 발생하네.
일단 이건 내일 해결해보자.

**Comment by eubinecto** [comment]
일단 wisdomifier를 깔끔하게 로드하는 목적은 달성함.
