### ISSUE TITLE
version_1 모델 훈련 & 저장하기

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/wisdomify#47]
## To-do's
- [x] version_1에 해당하는 데이터 설정하기
- [x] conf.json 에 version_1 설정 집어넣기
- [x] 그냥 train / test 스플릿을 해서 데이터를 저장해놓기.
- [x] 버전 1을 위한 준비 파튀!
- [ ] ainize 에서 version_1  트레이닝하기
